// Renders the query canvas in both themes so the syntax palette can be
// eyeballed and regressions caught.
//
//   flutter test test/sql_view_golden_test.dart --update-goldens
//
// google_fonts cannot fetch Fira Code in a test, so the goldens draw with a
// fallback face and the glyphs are blocks. That is fine for what these guard:
// which colour each kind of token gets, and that the gutter stays aligned.
import 'dart:io' show Platform;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_sql_converter/widgets/sql_view.dart';

// The goldens were generated on macOS; Windows rasterizes the fallback face
// differently (~7% pixel diff on the release runner), so the comparison only
// holds on the platform that drew them.
final _skipGoldens = !Platform.isMacOS;

const _sample = '''-- ============================================================================
-- Program: hasCancelledJobTriggerTypeItem (source/Prg_9408.xml)
-- Generated by MagicSoftSQL
-- ============================================================================

-- Global Parameter Declarations
DECLARE @dJobs_jobCompany INT = NULL;
DECLARE @p_status DECIMAL(5, 3) = NULL;

-- ----------------------------------------------------------------------------
-- Child Task (Sub-Program) ISN #4 (ID: 9408): checkForCancelledJob [Level 1]
-- ----------------------------------------------------------------------------
SELECT
    [dJobTaskDetails].[jtdJobID] AS [jtdJobID],
    [mChargeTypeMinCharge].[ctmEnabled] AS [ctmEnabled]
FROM [dJobTaskDetails] WITH (NOLOCK)
INNER JOIN [mChargeTypeMinCharge] WITH (NOLOCK)
    ON [mChargeTypeMinCharge].[ctmDepartment] = @dJobs_jobCompany
    AND [mChargeTypeMinCharge].[ctmEnabled] = 1
WHERE [dJobTaskDetails].[jtdJobID] BETWEEN 10 AND 20
  AND (ctmTriggerType = 'CANCELMYJOB')
ORDER BY [dJobTaskDetails].[jtdTaskDetID] DESC
;''';

Widget _harness(Brightness brightness) => MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(brightness: brightness),
      home: const Scaffold(body: SqlView(sql: _sample)),
    );

void main() {
  setUpAll(() => GoogleFonts.config.allowRuntimeFetching = false);

  testWidgets('query canvas, dark', (tester) async {
    await tester.binding.setSurfaceSize(const Size(900, 560));
    await tester.pumpWidget(_harness(Brightness.dark));
    await tester.pumpAndSettle();
    await expectLater(
      find.byType(SqlView),
      matchesGoldenFile('goldens/sql_view_dark.png'),
    );
  }, skip: _skipGoldens);

  testWidgets('query canvas, light', (tester) async {
    await tester.binding.setSurfaceSize(const Size(900, 560));
    await tester.pumpWidget(_harness(Brightness.light));
    await tester.pumpAndSettle();
    await expectLater(
      find.byType(SqlView),
      matchesGoldenFile('goldens/sql_view_light.png'),
    );
  }, skip: _skipGoldens);
}
