import '../models/unipaas_models.dart';

class SqlGeneratorService {
  String generateSql({
    required ParsedProgram program,
    required List<ProgramParameter> parameters,
    ParsedTask? selectedTask,
    bool injectValues = false,
  }) {
    final buffer = StringBuffer();

    final targetTasks = selectedTask != null ? [selectedTask] : program.allTasksFlattened;

    buffer.writeln('-- ============================================================================');
    buffer.writeln('-- Program: ${program.name} (${program.filename})');
    if (selectedTask != null) {
      buffer.writeln('-- Target Task: Task ISN ${selectedTask.taskIsn} - ${selectedTask.description} (Level ${selectedTask.level})');
    } else {
      buffer.writeln('-- Total Tasks: ${program.allTasksFlattened.length} (${program.tasks.length} Root, ${program.allTasksFlattened.length - program.tasks.length} Child Tasks)');
    }
    buffer.writeln('-- Generated by UniPaas SQL Converter');
    buffer.writeln('-- ============================================================================\n');

    // Build parameter lookup
    final paramMap = <String, ProgramParameter>{};
    for (final p in parameters) {
      paramMap[p.name] = p;
      paramMap[p.fieldId] = p;
    }

    final taskParamNames = targetTasks.expand((t) => t.parameters.map((p) => p.name)).toSet();

    if (!injectValues && parameters.any((p) => p.currentValue.isNotEmpty || p.isParameter)) {
      final globalParams = parameters.where((p) => (p.isParameter || p.currentValue.isNotEmpty) && !taskParamNames.contains(p.name)).toList();
      if (globalParams.isNotEmpty) {
        buffer.writeln('-- Global Parameter Declarations');
        for (final p in globalParams) {
          final sqlType = _mapToSqlType(p.type);
          final val = _formatSqlLiteral(p.currentValue, p.type);
          buffer.writeln('DECLARE @${p.name} $sqlType = $val;');
        }
        buffer.writeln();
      }
    }

    for (int i = 0; i < targetTasks.length; i++) {
      final task = targetTasks[i];
      final isChild = task.level > 0;
      final taskTypeLabel = isChild ? 'Child Task (Sub-Program)' : 'Main Task';

      buffer.writeln('-- ----------------------------------------------------------------------------');
      buffer.writeln('-- $taskTypeLabel ISN #${task.taskIsn}${task.taskId.isNotEmpty ? " (ID: ${task.taskId})" : ""}: ${task.description} [Level ${task.level}]');
      buffer.writeln('-- ----------------------------------------------------------------------------');

      if (!injectValues && task.parameters.isNotEmpty) {
        for (final p in task.parameters) {
          final sqlType = _mapToSqlType(p.type);
          final val = _formatSqlLiteral(p.currentValue, p.type);
          buffer.writeln('DECLARE @${p.name} $sqlType = $val;');
        }
      }

      final isMainEmpty = task.mainTableName.isEmpty || task.mainTableName == 'UnknownTable';

      if (isMainEmpty && task.joins.isNotEmpty && task.joins[0].mode == 'W') {
        final targetTable = task.joins[0].targetTableName;
        buffer.writeln('-- Link Write (Insert / Update operation) into [$targetTable]');
        if (task.joins[0].conditions.isNotEmpty) {
          buffer.writeln('IF NOT EXISTS (');
          buffer.writeln('    SELECT 1 FROM [$targetTable] WITH (NOLOCK)');
          for (int j = 0; j < task.joins[0].conditions.length; j++) {
            final cond = task.joins[0].conditions[j];
            final prefix = (j == 0) ? '    WHERE ' : '      AND ';
            final expr = _resolveExpression(cond.sourceExpression, paramMap, injectValues);
            buffer.writeln('$prefix[$targetTable].[${cond.targetColName}] = $expr');
          }
          buffer.writeln(')');
          buffer.writeln('BEGIN');
        }
        final indent = task.joins[0].conditions.isNotEmpty ? '    ' : '';
        buffer.writeln('${indent}INSERT INTO [$targetTable] (');
        for (int c = 0; c < task.columns.length; c++) {
          final col = task.columns[c];
          final comma = (c == task.columns.length - 1) ? '' : ',';
          buffer.writeln('$indent    [${col.colName}]$comma');
        }
        buffer.writeln('$indent) VALUES (');
        for (int c = 0; c < task.columns.length; c++) {
          final col = task.columns[c];
          final comma = (c == task.columns.length - 1) ? '' : ',';
          final valExpr = col.initExpression.isNotEmpty ? _resolveExpression(col.initExpression, paramMap, injectValues) : 'NULL';
          buffer.writeln('$indent    $valExpr$comma');
        }
        buffer.writeln('$indent);');
        if (task.joins[0].conditions.isNotEmpty) {
          buffer.writeln('END;\n');
        } else {
          buffer.writeln();
        }
        continue;
      }

      String mainTable = task.mainTableName;
      List<TableJoin> activeJoins = List.from(task.joins);
      List<WhereCondition> activeWheres = List.from(task.whereConditions);

      if ((mainTable.isEmpty || mainTable == 'UnknownTable') && activeJoins.isNotEmpty) {
        final promoted = activeJoins.removeAt(0);
        mainTable = promoted.targetTableName;
        for (final cond in promoted.conditions) {
          activeWheres.add(WhereCondition(
            tableName: mainTable,
            colName: cond.targetColName,
            operator: '=',
            valueExpression: cond.sourceExpression,
          ));
        }
      }

      final seenTables = <String>{if (mainTable.isNotEmpty && mainTable != 'UnknownTable') mainTable};
      final deduplicatedJoins = <TableJoin>[];
      for (final join in activeJoins) {
        if (seenTables.contains(join.targetTableName)) {
          for (final cond in join.conditions) {
            final exists = activeWheres.any((w) =>
                w.tableName == join.targetTableName &&
                w.colName == cond.targetColName &&
                w.valueExpression == cond.sourceExpression);
            if (!exists) {
              activeWheres.add(WhereCondition(
                tableName: join.targetTableName,
                colName: cond.targetColName,
                operator: '=',
                valueExpression: cond.sourceExpression,
              ));
            }
          }
        } else {
          seenTables.add(join.targetTableName);
          deduplicatedJoins.add(join);
        }
      }
      activeJoins = deduplicatedJoins;

      buffer.writeln('SELECT');
      if (task.columns.isEmpty) {
        buffer.writeln('    *');
      } else {
        final seenCols = <String>{};
        final uniqueCols = <SelectedColumn>[];
        for (final col in task.columns) {
          final key = '${col.tableName}.${col.colName}';
          if (!seenCols.contains(key)) {
            seenCols.add(key);
            uniqueCols.add(col);
          }
        }
        for (int c = 0; c < uniqueCols.length; c++) {
          final col = uniqueCols[c];
          final comma = (c == uniqueCols.length - 1) ? '' : ',';
          buffer.writeln('    [${col.tableName}].[${col.colName}] AS [${col.alias}]$comma');
        }
      }

      if (mainTable.isNotEmpty && mainTable != 'UnknownTable') {
        buffer.writeln('FROM [$mainTable] WITH (NOLOCK)');
      }

      for (final join in activeJoins) {
        buffer.writeln('${join.joinType} [${join.targetTableName}] WITH (NOLOCK)');
        if (join.conditions.isEmpty) {
          buffer.writeln('    ON 1 = 1');
        } else {
          for (int j = 0; j < join.conditions.length; j++) {
            final cond = join.conditions[j];
            final prefix = (j == 0) ? '    ON ' : '    AND ';
            final expr = _resolveExpression(cond.sourceExpression, paramMap, injectValues);
            buffer.writeln('$prefix[${join.targetTableName}].[${cond.targetColName}] = $expr');
          }
        }
      }

      if (activeWheres.isNotEmpty) {
        for (int w = 0; w < activeWheres.length; w++) {
          final cond = activeWheres[w];
          final prefix = (w == 0) ? 'WHERE ' : '  AND ';
          final expr = _resolveExpression(cond.valueExpression, paramMap, injectValues);
          buffer.writeln('$prefix[${cond.tableName}].[${cond.colName}] ${cond.operator} $expr');
        }
      }

      buffer.writeln(';\n');
    }

    return buffer.toString().trimRight();
  }

  String _resolveExpression(
    String expr,
    Map<String, ProgramParameter> paramMap,
    bool injectValues,
  ) {
    if (expr.startsWith('@')) {
      final paramName = expr.substring(1);
      final p = paramMap[paramName];
      if (p != null) {
        if (injectValues && p.currentValue.isNotEmpty) {
          return _formatSqlLiteral(p.currentValue, p.type);
        }
        return '@${p.name}';
      }
    }
    return expr;
  }

  String _mapToSqlType(String uniType) {
    switch (uniType.toUpperCase()) {
      case 'NUMERIC':
        return 'DECIMAL(18, 4)';
      case 'DATE':
        return 'DATETIME';
      case 'TIME':
        return 'TIME';
      case 'LOGICAL':
        return 'BIT';
      default:
        return 'NVARCHAR(255)';
    }
  }

  String _formatSqlLiteral(String value, String type) {
    if (value.isEmpty) return 'NULL';
    if (type.toUpperCase() == 'NUMERIC') {
      final numVal = num.tryParse(value);
      return numVal != null ? numVal.toString() : '0';
    }
    if (type.toUpperCase() == 'LOGICAL') {
      return (value == '1' || value.toUpperCase() == 'TRUE' || value.toUpperCase() == 'Y') ? '1' : '0';
    }
    return "'${value.replaceAll("'", "''")}'";
  }
}
