import '../models/unipaas_models.dart';

class SqlGeneratorService {
  /// [programNumber] is the program's position in the list, so task banners can
  /// be labelled the way uniPaaS Studio labels them: `#12.1`.
  String generateSql({
    required ParsedProgram program,
    required List<ProgramParameter> parameters,
    ParsedTask? selectedTask,
    bool injectValues = false,
    String programNumber = '',
  }) {
    final buffer = StringBuffer();

    final targetTasks = selectedTask != null ? [selectedTask] : program.allTasksFlattened;

    buffer.writeln('-- ============================================================================');
    buffer.writeln('-- Program: ${program.name} (${program.filename})');
    if (selectedTask != null) {
      buffer.writeln('-- Target Task: ${_taskNumber(selectedTask, programNumber)} '
          '${selectedTask.description} (ISN ${selectedTask.taskIsn}, level ${selectedTask.level})');
    } else {
      buffer.writeln('-- Total Tasks: ${program.allTasksFlattened.length} (${program.tasks.length} Root, ${program.allTasksFlattened.length - program.tasks.length} Child Tasks)');
    }
    buffer.writeln('-- Generated by UniPaas SQL Converter');
    buffer.writeln('-- ============================================================================\n');

    final paramMap = <String, ProgramParameter>{};
    for (final p in parameters) {
      paramMap[p.name] = p;
      if (p.fieldId.isNotEmpty) paramMap[p.fieldId] = p;
    }

    final taskParamNames = targetTasks.expand((t) => t.parameters.map((p) => p.name)).toSet();

    if (!injectValues) {
      _writeGlobalDeclarations(
        buffer: buffer,
        targetTasks: targetTasks,
        program: program,
        parameters: parameters,
        taskParamNames: taskParamNames,
      );
    }

    for (final task in targetTasks) {
      _writeTask(
        buffer: buffer,
        task: task,
        paramMap: paramMap,
        injectValues: injectValues,
        programNumber: programNumber,
      );
    }

    return buffer.toString().trimRight();
  }

  /// Task number in uniPaaS Studio's dotted form. Without a program number the
  /// path alone still locates the task inside its file.
  static String _taskNumber(ParsedTask task, String programNumber) {
    if (programNumber.isNotEmpty) return task.numberWithin(programNumber);
    return task.hierarchyPath.isEmpty ? '#main' : '#${task.hierarchyPath}';
  }

  // ---------------------------------------------------------------------------
  // Declarations
  // ---------------------------------------------------------------------------

  void _writeGlobalDeclarations({
    required StringBuffer buffer,
    required List<ParsedTask> targetTasks,
    required ParsedProgram program,
    required List<ProgramParameter> parameters,
    required Set<String> taskParamNames,
  }) {
    // Only declare what the generated statements actually reference.
    final used = StringBuffer();
    for (final task in targetTasks) {
      for (final join in task.joins) {
        for (final cond in join.conditions) {
          used.write(' ${cond.sourceExpression} ${cond.upperExpression}');
        }
      }
      for (final cond in task.whereConditions) {
        used.write(' ${cond.valueExpression} ${cond.upperExpression}');
      }
      for (final col in task.columns) {
        used.write(' ${col.initExpression}');
      }
      used.write(' ${task.sqlWhereClause}');
    }
    final usedText = used.toString();

    final declared = <String>{};
    final declarations = <String>[];

    void consider(String name, String type, String value) {
      if (taskParamNames.contains(name)) return;
      final cleanName = name.replaceAll(' ', '_');
      if (!usedText.contains('@$name') && !usedText.contains('@$cleanName')) return;
      if (!declared.add(cleanName)) return;
      declarations.add('DECLARE @$cleanName ${_mapToSqlType(type)} = $value;');
    }

    for (final p in parameters) {
      consider(p.name, p.type, _formatSqlLiteral(p.currentValue, p.type));
    }
    for (final g in program.mainProgramGlobals.values) {
      consider(g.name, g.sqlType, 'NULL');
    }

    if (declarations.isNotEmpty) {
      buffer.writeln('-- Global Parameter Declarations');
      for (final decl in declarations) {
        buffer.writeln(decl);
      }
      buffer.writeln();
    }
  }

  // ---------------------------------------------------------------------------
  // Task
  // ---------------------------------------------------------------------------

  void _writeTask({
    required StringBuffer buffer,
    required ParsedTask task,
    required Map<String, ProgramParameter> paramMap,
    required bool injectValues,
    String programNumber = '',
  }) {
    final kind = task.level > 0 ? 'child task' : 'main task';

    buffer.writeln('-- ----------------------------------------------------------------------------');
    buffer.writeln('-- Task ${_taskNumber(task, programNumber)}: ${task.description}');
    buffer.writeln('--   $kind, ISN ${task.taskIsn}'
        '${task.taskId.isNotEmpty ? ", program ID ${task.taskId}" : ""}, level ${task.level}');
    buffer.writeln('-- ----------------------------------------------------------------------------');

    if (!injectValues && task.parameters.isNotEmpty) {
      for (final p in task.parameters) {
        buffer.writeln('DECLARE @${p.name} ${_mapToSqlType(p.type)} = ${_formatSqlLiteral(p.currentValue, p.type)};');
      }
    }

    if (!task.hasDataSource) {
      buffer.writeln('-- This task has no data source; it is pure logic and produces no SQL.\n');
      return;
    }

    if (task.externalTables.isNotEmpty) {
      buffer.writeln('-- Uses tables from another uniPaaS component: '
          '${task.externalTables.join(', ')}.');
      buffer.writeln('-- Comps.xml names them but carries no column definitions, so their '
          'columns appear as Col_<n>.');
    }

    if (!task.mainSourceIsSql) {
      buffer.writeln('-- Main source is on the "${task.dataSource}" connection, which is not a SQL database.');
      buffer.writeln('-- No query generated.\n');
      return;
    }

    final isMainEmpty = task.mainTableName.isEmpty || task.mainTableName == 'UnknownTable';

    if (isMainEmpty && task.joins.isNotEmpty && task.joins.first.isWrite) {
      final join = task.joins.first;
      if (join.mode == 'A') {
        _writeInsert(
          buffer: buffer,
          task: task,
          join: join,
          paramMap: paramMap,
          injectValues: injectValues,
        );
      } else {
        _writeUpdate(
          buffer: buffer,
          task: task,
          join: join,
          paramMap: paramMap,
          injectValues: injectValues,
        );
      }
      return;
    }

    _writeSelect(
      buffer: buffer,
      task: task,
      paramMap: paramMap,
      injectValues: injectValues,
    );
  }

  // ---------------------------------------------------------------------------
  // Link Create -> INSERT
  // ---------------------------------------------------------------------------

  void _writeInsert({
    required StringBuffer buffer,
    required ParsedTask task,
    required TableJoin join,
    required Map<String, ProgramParameter> paramMap,
    required bool injectValues,
  }) {
    final target = join.targetTableName;
    buffer.writeln('-- Link Create into [$target]');

    // Prefer values the task actually assigns; fall back to any init
    // expression carried on the selected column.
    final values = <String, String>{};
    for (final col in task.columns.where((c) => c.tableObj == join.targetTableObj)) {
      if (col.initExpression.isNotEmpty) values[col.colName] = col.initExpression;
    }
    for (final a in task.assignments.where((a) => a.tableObj == join.targetTableObj)) {
      values[a.colName] = a.expression;
    }
    // A Link Create also seeds the record with its key values.
    for (final cond in join.conditions) {
      if (cond.operator == '=') {
        values.putIfAbsent(cond.targetColName, () => cond.sourceExpression);
      }
    }

    if (values.isEmpty) {
      buffer.writeln('-- No column values were assigned in this link.\n');
      return;
    }

    final guarded = join.conditions.isNotEmpty;
    if (guarded) {
      buffer.writeln('IF NOT EXISTS (');
      buffer.writeln('    SELECT 1 FROM [$target] WITH (NOLOCK)');
      for (int i = 0; i < join.conditions.length; i++) {
        final prefix = (i == 0) ? '    WHERE ' : '      AND ';
        buffer.writeln(prefix + _renderJoinCondition(target, join.conditions[i], paramMap, injectValues));
      }
      buffer.writeln(')');
      buffer.writeln('BEGIN');
    }

    final indent = guarded ? '    ' : '';
    final entries = values.entries.toList();
    buffer.writeln('${indent}INSERT INTO [$target] (');
    for (int i = 0; i < entries.length; i++) {
      buffer.writeln('$indent    [${entries[i].key}]${i == entries.length - 1 ? '' : ','}');
    }
    buffer.writeln('$indent) VALUES (');
    for (int i = 0; i < entries.length; i++) {
      final value = _resolveExpression(entries[i].value, paramMap, injectValues);
      buffer.writeln('$indent    $value${i == entries.length - 1 ? '' : ','}');
    }
    buffer.writeln('$indent);');
    buffer.writeln(guarded ? 'END;\n' : '');
  }

  // ---------------------------------------------------------------------------
  // Link Write -> UPDATE
  // ---------------------------------------------------------------------------

  /// A Link Write positions on an existing record and lets the task's Update
  /// operations change it, so the faithful statement is an UPDATE, not an
  /// INSERT of empty columns.
  void _writeUpdate({
    required StringBuffer buffer,
    required ParsedTask task,
    required TableJoin join,
    required Map<String, ProgramParameter> paramMap,
    required bool injectValues,
  }) {
    final target = join.targetTableName;
    final assignments = task.assignments.where((a) => a.tableObj == join.targetTableObj).toList();

    buffer.writeln('-- Link Write into [$target]');

    if (assignments.isEmpty) {
      buffer.writeln('-- The task locates a record here but assigns no columns to it.');
      if (join.conditions.isNotEmpty) {
        buffer.writeln('-- Located by:');
        for (final cond in join.conditions) {
          buffer.writeln('--   ${_renderJoinCondition(target, cond, paramMap, injectValues)}');
        }
      }
      buffer.writeln();
      return;
    }

    buffer.writeln('UPDATE [$target]');
    for (int i = 0; i < assignments.length; i++) {
      final a = assignments[i];
      final value = _resolveExpression(a.expression, paramMap, injectValues);
      final rhs = a.incremental ? '[$target].[${a.colName}] + $value' : value;
      buffer.writeln('${i == 0 ? '   SET ' : '     , '}[${a.colName}] = $rhs');
    }
    for (int i = 0; i < join.conditions.length; i++) {
      final prefix = (i == 0) ? ' WHERE ' : '   AND ';
      buffer.writeln(prefix + _renderJoinCondition(target, join.conditions[i], paramMap, injectValues));
    }
    buffer.writeln(';\n');
  }

  // ---------------------------------------------------------------------------
  // SELECT
  // ---------------------------------------------------------------------------

  void _writeSelect({
    required StringBuffer buffer,
    required ParsedTask task,
    required Map<String, ProgramParameter> paramMap,
    required bool injectValues,
  }) {
    var fromTable = task.mainTableName;
    var fromAlias = task.mainTableAlias;
    var joins = List<TableJoin>.from(task.joins);
    final wheres = List<WhereCondition>.from(task.whereConditions);

    // A task without a main source reads its first link as the record source.
    if ((fromTable.isEmpty || fromTable == 'UnknownTable') && joins.isNotEmpty) {
      final promoted = joins.removeAt(0);
      fromTable = promoted.targetTableName;
      fromAlias = promoted.alias;
      for (final cond in promoted.conditions) {
        wheres.add(WhereCondition(
          tableName: promoted.alias,
          colName: cond.targetColName,
          operator: cond.operator,
          valueExpression: cond.sourceExpression,
          upperExpression: cond.upperExpression,
        ));
      }
    }

    // Write links do not belong in a SELECT.
    final writeLinks = joins.where((j) => j.isWrite).toList();
    joins = joins.where((j) => !j.isWrite).toList();

    final nonSqlLinks = joins.where((j) => !j.isSqlSource).toList();
    joins = joins.where((j) => j.isSqlSource).toList();

    // Only columns of tables that survive into the query can be selected.
    final inScope = <String>{
      if (fromAlias.isNotEmpty) fromAlias,
      for (final join in joins) join.alias,
    };
    final columns = _dedupeColumns(
      task.columns.where((c) => inScope.contains(c.tableName)).toList(),
    );

    buffer.writeln('SELECT');
    if (columns.isEmpty) {
      buffer.writeln('    *');
    } else {
      final usedAliases = <String>{};
      for (int i = 0; i < columns.length; i++) {
        final col = columns[i];
        final comma = (i == columns.length - 1) ? '' : ',';
        buffer.writeln('    [${col.tableName}].[${col.colName}] '
            'AS [${_uniqueAlias(col, usedAliases)}]$comma');
      }
    }

    if (fromTable.isNotEmpty && fromTable != 'UnknownTable') {
      final aliasClause = fromAlias != fromTable && fromAlias.isNotEmpty ? ' AS [$fromAlias]' : '';
      buffer.writeln('FROM [$fromTable]$aliasClause WITH (NOLOCK)');
    }

    for (final join in joins) {
      if (join.needsTopOneApply) {
        _writeTopOneApply(buffer, join, paramMap, injectValues);
      } else {
        final aliasClause = join.needsAlias ? ' AS [${join.alias}]' : '';
        buffer.writeln('${join.joinType} [${join.targetTableName}]$aliasClause WITH (NOLOCK)');
        if (join.conditions.isEmpty) {
          buffer.writeln('    ON 1 = 1');
        } else {
          for (int i = 0; i < join.conditions.length; i++) {
            final prefix = (i == 0) ? '    ON ' : '    AND ';
            buffer.writeln(prefix + _renderJoinCondition(join.alias, join.conditions[i], paramMap, injectValues));
          }
        }
      }
    }

    final whereLines = <String>[
      for (final cond in wheres)
        _renderCondition(
          '[${cond.tableName}].[${cond.colName}]',
          cond.operator,
          cond.valueExpression,
          cond.upperExpression,
          paramMap,
          injectValues,
        ),
    ];
    if (task.sqlWhereClause.isNotEmpty) {
      whereLines.add('(${_resolveExpression(task.sqlWhereClause, paramMap, injectValues)})');
    }

    for (int i = 0; i < whereLines.length; i++) {
      buffer.writeln((i == 0 ? 'WHERE ' : '  AND ') + whereLines[i]);
    }

    if (task.orderBy.isNotEmpty) {
      final terms = task.orderBy
          .map((t) => '[${t.tableName}].[${t.colName}]${t.descending ? ' DESC' : ''}')
          .join(', ');
      buffer.writeln('ORDER BY $terms');
    }

    buffer.writeln(';');

    for (final join in nonSqlLinks) {
      buffer.writeln('-- Link to [${join.targetTableName}] omitted: it lives on a non-SQL connection.');
    }
    for (final join in writeLinks) {
      buffer.writeln('-- Note: this task also writes to [${join.targetTableName}] (Link ${join.mode == 'A' ? 'Create' : 'Write'}).');
    }
    buffer.writeln();
  }

  /// A Link Query keeps only the first matching record. Over a non-unique index
  /// a LEFT JOIN would multiply rows, so the faithful translation is a
  /// correlated TOP 1.
  void _writeTopOneApply(
    StringBuffer buffer,
    TableJoin join,
    Map<String, ProgramParameter> paramMap,
    bool injectValues,
  ) {
    final reason = join.conditions.isEmpty
        ? 'unconditioned, so uniPaaS reads the first record of index "${join.indexId}"'
        : 'index "${join.indexId}" does not identify a single row';
    buffer.writeln('-- Link Query: $reason');
    buffer.writeln('OUTER APPLY (');
    buffer.writeln('    SELECT TOP 1 *');
    buffer.writeln('    FROM [${join.targetTableName}] WITH (NOLOCK)');
    for (int i = 0; i < join.conditions.length; i++) {
      final prefix = (i == 0) ? '    WHERE ' : '      AND ';
      buffer.writeln(prefix + _renderJoinCondition(join.targetTableName, join.conditions[i], paramMap, injectValues));
    }
    if (join.indexOrder.isNotEmpty) {
      // Without an order "first record" would be arbitrary.
      // A descending link reads the index backwards, flipping each segment.
      final terms = join.indexOrder
          .map((t) => '[${join.targetTableName}].[${t.colName}]'
              '${t.descending != join.descending ? ' DESC' : ''}')
          .join(', ');
      buffer.writeln('    ORDER BY $terms');
    }
    buffer.writeln(') AS [${join.alias}]');
  }

  /// The same column name can arrive from two instances of a table, so output
  /// aliases are qualified until they are unique.
  String _uniqueAlias(SelectedColumn col, Set<String> used) {
    final base = col.alias.isNotEmpty ? col.alias : col.colName;
    if (used.add(base)) return base;

    final qualified = '${col.tableName}_$base';
    if (used.add(qualified)) return qualified;

    var n = 2;
    while (!used.add('${qualified}_$n')) {
      n++;
    }
    return '${qualified}_$n';
  }

  List<SelectedColumn> _dedupeColumns(List<SelectedColumn> columns) {
    final seen = <String>{};
    final unique = <SelectedColumn>[];
    for (final col in columns) {
      if (seen.add('${col.tableName}.${col.colName}')) unique.add(col);
    }
    return unique;
  }

  // ---------------------------------------------------------------------------
  // Condition rendering
  // ---------------------------------------------------------------------------

  String _renderJoinCondition(
    String qualifier,
    JoinCondition cond,
    Map<String, ProgramParameter> paramMap,
    bool injectValues,
  ) {
    return _renderCondition(
      '[$qualifier].[${cond.targetColName}]',
      cond.operator,
      cond.sourceExpression,
      cond.upperExpression,
      paramMap,
      injectValues,
    );
  }

  String _renderCondition(
    String lhs,
    String operator,
    String lower,
    String upper,
    Map<String, ProgramParameter> paramMap,
    bool injectValues,
  ) {
    final low = _resolveExpression(lower, paramMap, injectValues);
    if (operator == 'BETWEEN') {
      final high = _resolveExpression(upper, paramMap, injectValues);
      return '$lhs BETWEEN $low AND $high';
    }
    return '$lhs $operator $low';
  }

  // ---------------------------------------------------------------------------
  // Values
  // ---------------------------------------------------------------------------

  /// Substitutes literal values for `@parameters` when the caller asked for an
  /// executable query. String literals are left alone.
  String _resolveExpression(
    String expr,
    Map<String, ProgramParameter> paramMap,
    bool injectValues,
  ) {
    if (!injectValues || expr.isEmpty) return expr;

    final buffer = StringBuffer();
    var i = 0;
    while (i < expr.length) {
      final ch = expr[i];
      if (ch == "'") {
        final end = _endOfStringLiteral(expr, i);
        buffer.write(expr.substring(i, end));
        i = end;
        continue;
      }
      if (ch == '@') {
        final match = RegExp(r'^@([A-Za-z_][A-Za-z0-9_]*)').firstMatch(expr.substring(i));
        if (match != null) {
          final name = match.group(1)!;
          final p = paramMap[name];
          if (p != null && p.currentValue.isNotEmpty) {
            buffer.write(_formatSqlLiteral(p.currentValue, p.type));
          } else {
            buffer.write(match.group(0));
          }
          i += match.group(0)!.length;
          continue;
        }
      }
      buffer.write(ch);
      i++;
    }
    return buffer.toString();
  }

  static int _endOfStringLiteral(String s, int start) {
    var i = start + 1;
    while (i < s.length) {
      if (s[i] == "'") {
        if (i + 1 < s.length && s[i + 1] == "'") {
          i += 2;
          continue;
        }
        return i + 1;
      }
      i++;
    }
    return s.length;
  }

  /// Exposed so the parameter editor can label a value with the same type the
  /// DECLARE will use.
  static String sqlTypeFor(String uniType) => _mapToSqlType(uniType);

  static String _mapToSqlType(String uniType) {
    final upper = uniType.trim().toUpperCase();
    if (upper.startsWith('INT') ||
        upper.startsWith('BIGINT') ||
        upper.startsWith('NVARCHAR') ||
        upper.startsWith('VARCHAR') ||
        upper.startsWith('DECIMAL') ||
        upper.startsWith('NUMERIC') ||
        upper.startsWith('DATETIME') ||
        upper.startsWith('DATE') ||
        upper.startsWith('TIME') ||
        upper.startsWith('BIT')) {
      return uniType;
    }
    switch (upper) {
      case 'NUMERIC':
        return 'INT';
      case 'DATE':
        return 'DATETIME';
      case 'TIME':
        return 'TIME';
      case 'LOGICAL':
        return 'BIT';
      default:
        return 'NVARCHAR(255)';
    }
  }

  static String _formatSqlLiteral(String value, String type) {
    if (value.isEmpty) return 'NULL';
    final upper = type.trim().toUpperCase();
    if (upper == 'NUMERIC' ||
        upper.startsWith('INT') ||
        upper.startsWith('BIGINT') ||
        upper.startsWith('DECIMAL')) {
      final numVal = num.tryParse(value);
      return numVal != null ? numVal.toString() : '0';
    }
    if (upper == 'LOGICAL' || upper == 'BIT') {
      final v = value.toUpperCase();
      return (v == '1' || v == 'TRUE' || v == 'Y') ? '1' : '0';
    }
    return "'${value.replaceAll("'", "''")}'";
  }
}
